/**:
  ros__parameters:
    wheel_radius: 0.344 # XRM - The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.215 # XRM - The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 2.95 # XRM - between front wheel center and rear wheel center
    wheel_tread: 1.64 # between left wheel center and right wheel center
    front_overhang: 1.0 # between front wheel center and vehicle front
    rear_overhang: 1.1 # between rear wheel center and vehicle rear
    left_overhang: 0.128 # between left wheel center and vehicle left
    right_overhang: 0.128 # between right wheel center and vehicle right
    vehicle_height: 2.5
    max_steer_angle: 0.70 # [rad]
